server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
  flyway:
    baseline-on-migrate: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

valdef:
  user: user@user.ru
  password: password